apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-name-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_USERNAME/helm-multi-cluster-deployment'
    targetRevision: HEAD
    path: helm-charts/app-name
    helm:
      valueFiles:
        - values/dev-values.yaml
  destination:
    server: 'https://api.cluster1.openshift.com'
    namespace: app-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
